version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_database
    restart: always
    environment:
      MYSQL_DATABASE: cricinformer
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    image: cricinformerimage
    container_name: spring_boot_app
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cricinformer?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local
